const CATEGORIES = [
  { id:'all',      label:'Все товары',   emoji:'🛒', color:'#2d6a4f' },
  { id:'fruits',   label:'Фрукты',       emoji:'🍎', color:'#e63946' },
  { id:'veggies',  label:'Овощи',        emoji:'🥦', color:'#2d6a4f' },
  { id:'berries',  label:'Ягоды',        emoji:'🍓', color:'#9b2226' },
  { id:'drinks',   label:'Напитки',      emoji:'🧃', color:'#0077b6' },
  { id:'dairy',    label:'Молочные',     emoji:'🥛', color:'#6d6875' },
  { id:'bakery',   label:'Выпечка',      emoji:'🥐', color:'#c77dff' },  
  { id:'nuts',     label:'Орехи и сухофр.',emoji:'🥜', color:'#7b3f00' },
  { id:'greens',   label:'Зелень',       emoji:'🌿', color:'#457b33' },
  { id:'exotic',   label:'Экзотика',     emoji:'🌴', color:'#e76f00' },
];

const PRODUCTS = [
  /* ── FRUITS (20) ── */
  {id:1,  name:'Яблоки Гала',        cat:'fruits',  price:89,  oldPrice:null, rating:4.8, votes:1240, pop:95, emoji:'🍎', unit:'кг',  desc:'Сладкие, хрустящие. Урожай этого сезона из Краснодарского края.', badge:null},
  {id:2,  name:'Бананы Ecuador',     cat:'fruits',  price:79,  oldPrice:99,  rating:4.6, votes:980,  pop:90, emoji:'🍌', unit:'кг',  desc:'Отборные бананы из Эквадора. Идеально дозрелые.', badge:'Хит'},
  {id:3,  name:'Апельсины Navel',    cat:'fruits',  price:139, oldPrice:null, rating:4.7, votes:876,  pop:85, emoji:'🍊', unit:'кг',  desc:'Сочные апельсины без косточек. Богаты витамином C.', badge:null},
  {id:4,  name:'Манго Alphonso',     cat:'fruits',  price:299, oldPrice:349, rating:4.9, votes:654,  pop:82, emoji:'🥭', unit:'шт',  desc:'Король манго. Невероятный аромат и вкус, без волокон.', badge:'Premium'},
  {id:5,  name:'Груши Конференс',    cat:'fruits',  price:119, oldPrice:null, rating:4.5, votes:543,  pop:70, emoji:'🍐', unit:'кг',  desc:'Сочные и нежные. Долго хранятся.', badge:null},
  {id:6,  name:'Виноград кишмиш',    cat:'fruits',  price:219, oldPrice:269, rating:4.7, votes:721,  pop:88, emoji:'🍇', unit:'кг',  desc:'Без косточек. Сладкий, хрустящий.', badge:'Скидка'},
  {id:7,  name:'Авокадо Hass',       cat:'fruits',  price:169, oldPrice:null, rating:4.8, votes:1100, pop:92, emoji:'🥑', unit:'шт',  desc:'Идеально спелое. Кремовая текстура, ореховый вкус.', badge:'Хит'},
  {id:8,  name:'Лимоны Сицилия',    cat:'fruits',  price:99,  oldPrice:null, rating:4.4, votes:432,  pop:75, emoji:'🍋', unit:'кг',  desc:'Тонкая кожура, много сока. Без обработки воском.', badge:null},
  {id:9,  name:'Персики',            cat:'fruits',  price:249, oldPrice:null, rating:4.9, votes:887,  pop:91, emoji:'🍑', unit:'кг',  desc:'Сезонные персики. Невероятно ароматные.', badge:'Сезон'},
  {id:10, name:'Сливы Чернослив',    cat:'fruits',  price:179, oldPrice:null, rating:4.6, votes:398,  pop:72, emoji:'🫐', unit:'кг',  desc:'Крупные, сладкие. Отлично подходят для варенья.', badge:null},
  {id:11, name:'Арбуз',              cat:'fruits',  price:39,  oldPrice:null, rating:4.8, votes:1560, pop:96, emoji:'🍉', unit:'кг',  desc:'Сладкий, с тонкой коркой. Проверяем каждый.', badge:'Хит'},
  {id:12, name:'Дыня Торпеда',       cat:'fruits',  price:59,  oldPrice:null, rating:4.7, votes:678,  pop:83, emoji:'🍈', unit:'кг',  desc:'Медовая, очень ароматная. Узбекский сорт.', badge:null},
  {id:13, name:'Айва',               cat:'fruits',  price:149, oldPrice:null, rating:4.3, votes:213,  pop:55, emoji:'🍏', unit:'кг',  desc:'Ароматная, для джемов и выпечки.', badge:null},
  {id:14, name:'Хурма Королёк',      cat:'fruits',  price:199, oldPrice:239, rating:4.8, votes:567,  pop:80, emoji:'🍊', unit:'шт',  desc:'Без терпкости. Шоколадная мякоть.', badge:'Скидка'},
  {id:15, name:'Гранат',             cat:'fruits',  price:189, oldPrice:null, rating:4.7, votes:445,  pop:78, emoji:'🍎', unit:'шт',  desc:'Крупный, сочный. Иранский сорт.', badge:null},
  {id:16, name:'Киви',               cat:'fruits',  price:89,  oldPrice:null, rating:4.6, votes:876,  pop:87, emoji:'🥝', unit:'шт',  desc:'Богаты витамином C. Нежная мякоть.', badge:null},
  {id:17, name:'Ананас',             cat:'fruits',  price:259, oldPrice:299, rating:4.7, votes:543,  pop:81, emoji:'🍍', unit:'шт',  desc:'Сладкий, спелый. Из Коста-Рики.', badge:'Скидка'},
  {id:18, name:'Папайя',             cat:'fruits',  price:349, oldPrice:null, rating:4.5, votes:234,  pop:60, emoji:'🍈', unit:'шт',  desc:'Тропический вкус. Богата ферментами.', badge:null},
  {id:19, name:'Яблоки Симиренко',   cat:'fruits',  price:79,  oldPrice:null, rating:4.4, votes:567,  pop:73, emoji:'🍏', unit:'кг',  desc:'Кисло-сладкие, зелёные. Классика.', badge:null},
  {id:20, name:'Черешня',            cat:'fruits',  price:499, oldPrice:599, rating:4.9, votes:1230, pop:93, emoji:'🍒', unit:'500г', desc:'Крупная, сладкая. Краснодарский сезон.', badge:'Premium'},

  /* ── VEGGIES (18) ── */
  {id:21, name:'Морковь',            cat:'veggies', price:49,  oldPrice:null, rating:4.5, votes:987,  pop:88, emoji:'🥕', unit:'кг',  desc:'Сочная, сладкая. Фермерская, немытая.', badge:null},
  {id:22, name:'Брокколи',           cat:'veggies', price:149, oldPrice:null, rating:4.6, votes:654,  pop:79, emoji:'🥦', unit:'шт',  desc:'Плотные соцветия. Богата белком и витаминами.', badge:null},
  {id:23, name:'Помидоры черри',     cat:'veggies', price:189, oldPrice:219, rating:4.8, votes:1100, pop:91, emoji:'🍅', unit:'500г', desc:'Сладкие, сочные. Идеальны для салатов.', badge:'Хит'},
  {id:24, name:'Томаты Бычье сердце',cat:'veggies', price:229, oldPrice:null, rating:4.7, votes:765,  pop:85, emoji:'🍅', unit:'кг',  desc:'Мясистые, малокислотные. Отличны для бутербродов.', badge:null},
  {id:25, name:'Огурцы',             cat:'veggies', price:89,  oldPrice:null, rating:4.4, votes:876,  pop:87, emoji:'🥒', unit:'кг',  desc:'Хрустящие, ароматные. С тонкой кожурой.', badge:null},
  {id:26, name:'Болгарский перец',   cat:'veggies', price:159, oldPrice:189, rating:4.5, votes:543,  pop:77, emoji:'🫑', unit:'кг',  desc:'Ассорти: красный, жёлтый, оранжевый.', badge:'Скидка'},
  {id:27, name:'Картофель молодой',  cat:'veggies', price:69,  oldPrice:null, rating:4.3, votes:1234, pop:92, emoji:'🥔', unit:'кг',  desc:'Тонкая кожура. Варится быстро.', badge:'Сезон'},
  {id:28, name:'Лук красный',        cat:'veggies', price:69,  oldPrice:null, rating:4.4, votes:432,  pop:79, emoji:'🧅', unit:'кг',  desc:'Мягче обычного. Идеален в свежих салатах.', badge:null},
  {id:29, name:'Чеснок',             cat:'veggies', price:99,  oldPrice:null, rating:4.6, votes:678,  pop:82, emoji:'🧄', unit:'шт',  desc:'Крупная головка. Душистый, острый.', badge:null},
  {id:30, name:'Баклажан',           cat:'veggies', price:129, oldPrice:null, rating:4.4, votes:345,  pop:71, emoji:'🍆', unit:'шт',  desc:'Молодые, без горечи. Для запекания и рагу.', badge:null},
  {id:31, name:'Кабачок цукини',     cat:'veggies', price:109, oldPrice:null, rating:4.5, votes:456,  pop:75, emoji:'🥒', unit:'шт',  desc:'Нежные. Хороши гриль или в салате.', badge:null},
  {id:32, name:'Свёкла',             cat:'veggies', price:49,  oldPrice:null, rating:4.3, votes:567,  pop:73, emoji:'🟤', unit:'кг',  desc:'Тёмная, сладкая. Отварная или для борща.', badge:null},
  {id:33, name:'Капуста белокочанная',cat:'veggies',price:39,  oldPrice:null, rating:4.2, votes:765,  pop:80, emoji:'🥬', unit:'шт',  desc:'Плотный кочан. Хрустящая.', badge:null},
  {id:34, name:'Капуста цветная',    cat:'veggies', price:159, oldPrice:null, rating:4.6, votes:432,  pop:74, emoji:'🥦', unit:'шт',  desc:'Снежно-белая. Нежный вкус.', badge:null},
  {id:35, name:'Тыква Хоккайдо',    cat:'veggies', price:89,  oldPrice:null, rating:4.7, votes:345,  pop:70, emoji:'🎃', unit:'кг',  desc:'Оранжевая, с ореховым ароматом. Кожура съедобна.', badge:null},
  {id:36, name:'Спаржа',             cat:'veggies', price:349, oldPrice:null, rating:4.8, votes:234,  pop:65, emoji:'🌿', unit:'300г', desc:'Зелёная, свежая. Готовится за 5 минут.', badge:'Premium'},
  {id:37, name:'Сельдерей черешковый',cat:'veggies',price:129, oldPrice:null, rating:4.5, votes:312,  pop:68, emoji:'🥬', unit:'шт',  desc:'Хрустящий, ароматный. Отличен в смузи.', badge:null},
  {id:38, name:'Шампиньоны',         cat:'veggies', price:159, oldPrice:189, rating:4.7, votes:890,  pop:86, emoji:'🍄', unit:'500г', desc:'Крупные, свежие. Ежедневный завоз.', badge:'Скидка'},

  /* ── BERRIES (10) ── */
  {id:39, name:'Клубника',           cat:'berries', price:399, oldPrice:499, rating:4.9, votes:2100, pop:97, emoji:'🍓', unit:'500г', desc:'Крупная, ароматная. Краснодарская, без химии.', badge:'Хит'},
  {id:40, name:'Черника',            cat:'berries', price:349, oldPrice:null, rating:4.8, votes:987,  pop:90, emoji:'🫐', unit:'250г', desc:'Из карельских лесов. Богата антиоксидантами.', badge:null},
  {id:41, name:'Малина',             cat:'berries', price:329, oldPrice:null, rating:4.7, votes:765,  pop:86, emoji:'🍒', unit:'250г', desc:'Сладкая, нежная. Только с грядки.', badge:'Сезон'},
  {id:42, name:'Голубика',           cat:'berries', price:379, oldPrice:null, rating:4.8, votes:654,  pop:84, emoji:'🫐', unit:'250г', desc:'Крупная садовая. Плотная, хрустящая.', badge:null},
  {id:43, name:'Ежевика',            cat:'berries', price:359, oldPrice:null, rating:4.7, votes:432,  pop:79, emoji:'🍇', unit:'250г', desc:'Сладко-кислая, сочная. Прямо с куста.', badge:null},
  {id:44, name:'Смородина чёрная',   cat:'berries', price:249, oldPrice:null, rating:4.6, votes:543,  pop:75, emoji:'🍇', unit:'300г', desc:'Кисловатая, ароматная. Идеальна для варенья.', badge:null},
  {id:45, name:'Смородина красная',  cat:'berries', price:229, oldPrice:null, rating:4.5, votes:345,  pop:70, emoji:'🫐', unit:'300г', desc:'Ягоды на веточках. Очень сочная.', badge:null},
  {id:46, name:'Крыжовник',          cat:'berries', price:199, oldPrice:null, rating:4.4, votes:234,  pop:62, emoji:'🟢', unit:'300г', desc:'Зелёный и сладкий. Фермерский.', badge:null},
  {id:47, name:'Вишня',              cat:'berries', price:299, oldPrice:null, rating:4.8, votes:876,  pop:88, emoji:'🍒', unit:'500г', desc:'Тёмная, кисло-сладкая. Крупная, без трещин.', badge:'Сезон'},
  {id:48, name:'Физалис',            cat:'berries', price:289, oldPrice:null, rating:4.5, votes:178,  pop:58, emoji:'🟡', unit:'150г', desc:'В бумажных «фонариках». Экзотический вкус.', badge:null},

  /* ── DRINKS (12) ── */
  {id:49, name:'Сок апельсиновый',   cat:'drinks',  price:169, oldPrice:199, rating:4.7, votes:987,  pop:93, emoji:'🧃', unit:'1л',  desc:'Свежевыжатый, без сахара и консервантов. Охлаждённый.', badge:'Хит'},
  {id:50, name:'Вода Evian',         cat:'drinks',  price:129, oldPrice:null, rating:4.8, votes:1234, pop:89, emoji:'💧', unit:'1л',  desc:'Природная горная вода. Французские Альпы.', badge:null},
  {id:51, name:'Кофе в зёрнах',      cat:'drinks',  price:599, oldPrice:699, rating:4.9, votes:876,  pop:91, emoji:'☕', unit:'250г', desc:'Single Origin Ethiopia. Обжарка на этой неделе.', badge:'Premium'},
  {id:52, name:'Зелёный чай Matcha', cat:'drinks',  price:549, oldPrice:null, rating:4.9, votes:654,  pop:87, emoji:'🍵', unit:'50г',  desc:'Церемониальный grade. Из Уджи, Япония.', badge:'Premium'},
  {id:53, name:'Смузи Тропик',       cat:'drinks',  price:199, oldPrice:null, rating:4.6, votes:543,  pop:83, emoji:'🥤', unit:'330мл',desc:'Манго, маракуйя, банан. Без сахара.', badge:null},
  {id:54, name:'Комбуча Имбирь',     cat:'drinks',  price:219, oldPrice:null, rating:4.7, votes:432,  pop:78, emoji:'🫙', unit:'330мл',desc:'Живой, ферментированный. Пробиотики.', badge:null},
  {id:55, name:'Лимонад домашний',   cat:'drinks',  price:189, oldPrice:219, rating:4.5, votes:345,  pop:74, emoji:'🍋', unit:'500мл',desc:'На натуральном лимонном соке с мятой.', badge:'Скидка'},
  {id:56, name:'Молочный коктейль',  cat:'drinks',  price:249, oldPrice:null, rating:4.7, votes:567,  pop:81, emoji:'🥛', unit:'400мл',desc:'Клубничный. Без загустителей.', badge:null},
  {id:57, name:'Кокосовая вода',     cat:'drinks',  price:179, oldPrice:null, rating:4.6, votes:432,  pop:77, emoji:'🥥', unit:'330мл',desc:'Натуральная. Идеальна после тренировки.', badge:null},
  {id:58, name:'Сок томатный',       cat:'drinks',  price:99,  oldPrice:null, rating:4.4, votes:654,  pop:76, emoji:'🍅', unit:'1л',  desc:'Из свежих помидоров. Густой.', badge:null},
  {id:59, name:'Иван-чай',           cat:'drinks',  price:299, oldPrice:null, rating:4.8, votes:345,  pop:72, emoji:'🌺', unit:'50г',  desc:'Ферментированный. Из Алтайского края.', badge:null},
  {id:60, name:'Холодный кофе',      cat:'drinks',  price:259, oldPrice:null, rating:4.8, votes:678,  pop:85, emoji:'🧊', unit:'330мл',desc:'Cold brew. 12 часов экстракции.', badge:'Хит'},

  /* ── DAIRY (8) ── */
  {id:61, name:'Молоко 3.2%',        cat:'dairy',   price:99,  oldPrice:null, rating:4.6, votes:1456, pop:94, emoji:'🥛', unit:'1л',  desc:'Фермерское, пастеризованное. Ежедневный завоз.', badge:null},
  {id:62, name:'Творог зернистый',   cat:'dairy',   price:149, oldPrice:null, rating:4.7, votes:876,  pop:86, emoji:'🧀', unit:'200г', desc:'5%. Рассыпчатый, нежный.', badge:null},
  {id:63, name:'Сметана 20%',        cat:'dairy',   price:119, oldPrice:null, rating:4.5, votes:765,  pop:83, emoji:'🥣', unit:'300г', desc:'Густая, сливочная. Без крахмала.', badge:null},
  {id:64, name:'Йогурт греческий',   cat:'dairy',   price:149, oldPrice:179, rating:4.8, votes:987,  pop:88, emoji:'🫙', unit:'250г', desc:'Без добавок. 10% жирности. Отличен с ягодами.', badge:'Хит'},
  {id:65, name:'Масло сливочное 82%',cat:'dairy',   price:219, oldPrice:null, rating:4.8, votes:765,  pop:85, emoji:'🧈', unit:'200г', desc:'Вологодское. Без растительных жиров.', badge:'Premium'},
  {id:66, name:'Сыр Моцарелла',      cat:'dairy',   price:299, oldPrice:349, rating:4.7, votes:654,  pop:82, emoji:'🧀', unit:'125г', desc:'Мягкая, в рассоле. Итальянская рецептура.', badge:'Скидка'},
  {id:67, name:'Кефир 3.2%',         cat:'dairy',   price:89,  oldPrice:null, rating:4.5, votes:876,  pop:80, emoji:'🥛', unit:'1л',  desc:'Живые культуры. Мягкая кислинка.', badge:null},
  {id:68, name:'Ряженка',            cat:'dairy',   price:89,  oldPrice:null, rating:4.4, votes:543,  pop:76, emoji:'🥛', unit:'500мл',desc:'Топлёное молоко с закваской. Традиционная.', badge:null},

  /* ── BAKERY (8) ── */
  {id:69, name:'Круассан масляный',  cat:'bakery',  price:119, oldPrice:null, rating:4.9, votes:1340, pop:94, emoji:'🥐', unit:'шт',  desc:'Слоёное тесто на настоящем сливочном масле.', badge:'Хит'},
  {id:70, name:'Хлеб на закваске',   cat:'bakery',  price:169, oldPrice:null, rating:4.8, votes:987,  pop:89, emoji:'🍞', unit:'шт',  desc:'48 часов ферментации. Хрустящая корочка.', badge:'Premium'},
  {id:71, name:'Чиабатта',           cat:'bakery',  price:149, oldPrice:null, rating:4.7, votes:654,  pop:82, emoji:'🥖', unit:'шт',  desc:'С оливковым маслом. Хрустящая снаружи.', badge:null},
  {id:72, name:'Булочка с корицей',  cat:'bakery',  price:99,  oldPrice:null, rating:4.8, votes:876,  pop:86, emoji:'🧁', unit:'шт',  desc:'Синнабон-стиль. Сочная, с кремом.', badge:null},
  {id:73, name:'Багет французский',  cat:'bakery',  price:89,  oldPrice:null, rating:4.6, votes:765,  pop:84, emoji:'🥖', unit:'шт',  desc:'Классический. Тонкая хрустящая корочка.', badge:null},
  {id:74, name:'Пита цельнозерновая',cat:'bakery',  price:79,  oldPrice:99,  rating:4.4, votes:432,  pop:73, emoji:'🫓', unit:'4шт', desc:'Мягкие, отлично открываются. Для шаурмы.', badge:'Скидка'},
  {id:75, name:'Тарт лимонный',      cat:'bakery',  price:249, oldPrice:null, rating:4.9, votes:543,  pop:80, emoji:'🥧', unit:'шт',  desc:'Лимонный крем, хрустящее тесто. Ручная работа.', badge:'Premium'},
  {id:76, name:'Эклер шоколадный',   cat:'bakery',  price:129, oldPrice:null, rating:4.8, votes:678,  pop:83, emoji:'🍫', unit:'шт',  desc:'С заварным кремом и шоколадной глазурью.', badge:null},

  /* ── NUTS (8) ── */
  {id:77, name:'Кешью жареный',      cat:'nuts',    price:599, oldPrice:699, rating:4.8, votes:765,  pop:88, emoji:'🥜', unit:'200г', desc:'Слабосолёный. Урожай этого года, Вьетнам.', badge:'Скидка'},
  {id:78, name:'Миндаль',            cat:'nuts',    price:549, oldPrice:null, rating:4.7, votes:654,  pop:83, emoji:'🌰', unit:'200г', desc:'Сырой, целый. Калифорния. Много белка.', badge:null},
  {id:79, name:'Грецкие орехи',      cat:'nuts',    price:399, oldPrice:null, rating:4.6, votes:876,  pop:85, emoji:'🌰', unit:'200г', desc:'Крупные, половинки. Украина.', badge:null},
  {id:80, name:'Фисташки',           cat:'nuts',    price:649, oldPrice:null, rating:4.9, votes:987,  pop:91, emoji:'🫘', unit:'150г', desc:'Иранские. Крупные, раскрытые, солёные.', badge:'Premium'},
  {id:81, name:'Финики Medjool',     cat:'nuts',    price:449, oldPrice:499, rating:4.9, votes:765,  pop:87, emoji:'🌴', unit:'250г', desc:'«Король фиников». Мясистые, карамельные.', badge:'Хит'},
  {id:82, name:'Курага',             cat:'nuts',    price:299, oldPrice:null, rating:4.6, votes:543,  pop:78, emoji:'🟡', unit:'200г', desc:'Натуральная, без SO2. Тёмная, сладкая.', badge:null},
  {id:83, name:'Изюм золотой',       cat:'nuts',    price:199, oldPrice:null, rating:4.4, votes:432,  pop:72, emoji:'🍇', unit:'200г', desc:'Мягкий, сочный. Из кишмиша.', badge:null},
  {id:84, name:'Семена чиа',         cat:'nuts',    price:299, oldPrice:null, rating:4.7, votes:345,  pop:74, emoji:'⚫', unit:'200г', desc:'Богаты омега-3. Из Боливии.', badge:null},

  /* ── GREENS (6) ── */
  {id:85, name:'Базилик зелёный',    cat:'greens',  price:79,  oldPrice:null, rating:4.7, votes:543,  pop:82, emoji:'🌿', unit:'пучок',desc:'Ароматный, нежный. Итальянский сорт.', badge:null},
  {id:86, name:'Руккола',            cat:'greens',  price:99,  oldPrice:null, rating:4.6, votes:432,  pop:79, emoji:'🥬', unit:'пучок',desc:'Пикантная, перечная. Для пиццы и салатов.', badge:null},
  {id:87, name:'Шпинат',             cat:'greens',  price:89,  oldPrice:null, rating:4.5, votes:654,  pop:76, emoji:'🥬', unit:'пучок',desc:'Молодой, нежный. Богат железом.', badge:null},
  {id:88, name:'Кинза',              cat:'greens',  price:59,  oldPrice:null, rating:4.3, votes:345,  pop:70, emoji:'🌿', unit:'пучок',desc:'Свежая, душистая. Для шашлыка и супов.', badge:null},
  {id:89, name:'Укроп',              cat:'greens',  price:49,  oldPrice:null, rating:4.4, votes:876,  pop:84, emoji:'🌿', unit:'пучок',desc:'Пышный пучок. Только что с грядки.', badge:null},
  {id:90, name:'Мята',               cat:'greens',  price:79,  oldPrice:null, rating:4.7, votes:432,  pop:77, emoji:'🍃', unit:'пучок',desc:'Свежая перечная. Для напитков и десертов.', badge:null},

  /* ── EXOTIC (6) ── */
  {id:91, name:'Личи',               cat:'exotic',  price:499, oldPrice:null, rating:4.8, votes:234,  pop:68, emoji:'🍬', unit:'300г', desc:'Сочные, ароматные. Из Вьетнама.', badge:'Premium'},
  {id:92, name:'Рамбутан',           cat:'exotic',  price:549, oldPrice:null, rating:4.7, votes:178,  pop:62, emoji:'🔴', unit:'300г', desc:'«Лохматый» фрукт. Сладкий, освежающий.', badge:null},
  {id:93, name:'Карамбола',          cat:'exotic',  price:299, oldPrice:null, rating:4.5, votes:145,  pop:58, emoji:'⭐', unit:'шт',  desc:'Звёздчатый фрукт. Кисло-сладкий.', badge:null},
  {id:94, name:'Маракуйя',           cat:'exotic',  price:199, oldPrice:null, rating:4.7, votes:312,  pop:67, emoji:'🟣', unit:'шт',  desc:'Интенсивный аромат. Кислинка и сладость.', badge:null},
  {id:95, name:'Дракон фрукт',       cat:'exotic',  price:349, oldPrice:null, rating:4.6, votes:256,  pop:65, emoji:'🌵', unit:'шт',  desc:'Питайя. Яркая мякоть, нежный вкус.', badge:null},
  {id:96, name:'Джекфрут',           cat:'exotic',  price:699, oldPrice:null, rating:4.8, votes:156,  pop:60, emoji:'💛', unit:'кг',  desc:'Огромный, сладкий. Заменитель мяса.', badge:'Premium'},
];
